/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux clpc53.cs.ox.ac.uk 3.1.0-7.fc16.x86_64 x86_64"
#define LGL_COMPILED "Sat Dec 28 19:45:44 GMT 2013"
#define LGL_RELEASED "Wed Oct 16 17:03:36 CEST 2013"
#define LGL_VERSION "ats"
#define LGL_ID "57807c8f410a9e676816984a0ad0c410e485bcae"
