/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux chaitanya 3.13.0-88-generic x86_64"
#define LGL_COMPILED "Wed Jun 15 19:24:21 IST 2016"
#define LGL_RELEASED "Wed Oct 16 17:03:36 CEST 2013"
#define LGL_VERSION "ats"
#define LGL_ID "57807c8f410a9e676816984a0ad0c410e485bcae"
