/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux svs-pc 3.16.0-50-generic x86_64"
#define LGL_COMPILED "Mon Oct 26 20:28:22 IST 2015"
#define LGL_RELEASED "Wed Oct 16 17:03:36 CEST 2013"
#define LGL_VERSION "ats"
#define LGL_ID "57807c8f410a9e676816984a0ad0c410e485bcae"
