#!/bin/sh
#
# Copyright (c) 2008-2009
#
# School of Computing, University of Utah,
# Salt Lake City, UT 84112, USA
#
# and the Gauss Group
# http://www.cs.utah.edu/formal_verification
#
# See LICENSE for licensing information
#

exec "/usr/bin/mpicxx" "-L/home/ssharma/svs-research/isp-versions/mopper-spo/lib" "-I/home/ssharma/svs-research/isp-versions/mopper-spo/include/isp" -Wl,-rpath=/home/ssharma/svs-research/isp-versions/mopper-spo/lib -include isp.h $* -lisp_prof
