#!/bin/sh
#
# Copyright (c) 2008-2009
#
# School of Computing, University of Utah,
# Salt Lake City, UT 84112, USA
#
# and the Gauss Group
# http://www.cs.utah.edu/formal_verification
#
# See LICENSE for licensing information
#

/usr/bin/java -jar "/home/ssharma/svs-research/isp-versions/isp-predictive-binary/bin/ispui.jar" $* 
